Repository team-asos/asos-server, pull requests merged in 2021-11, with the labels that each got.

#15 [PR] Inquire 테이블 변경
  src/inquire/inquire.entity.ts
Labels: fix

#16 feat: User 엔티티에 사원 번호 추가 및 dto 대응
  src/user/dtos/create-user.dto.ts
  src/user/user.entity.ts
Labels: enhancement

#24 [PR] 예약 관련 API 추가 개발
  src/auth/auth.controller.ts
  src/common/utils/errors/ErrorMessage.ts
  src/config/swagger/setup.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/user/dtos/create-user.dto.ts
  src/user/user.entity.ts
  src/user/user.service.ts
Labels: enhancement

#28 좌석, 회의실 API 구현
  src/floor/floor.entity.ts
  src/room/dtos/update-room.dto.ts
  src/room/room.controller.ts
  src/room/room.entity.ts
  src/room/room.repository.ts
  src/room/room.service.ts
  src/seat/dtos/create-seat.dto.ts
  src/seat/dtos/update-seat.dto.ts
  src/seat/seat.controller.ts
  src/seat/seat.entity.ts
  src/seat/seat.repository.ts
  src/seat/seat.service.ts
Labels: enhancement

#30 Feat: 층 API 구현
  src/common/utils/errors/ErrorMessage.ts
  src/facility/facility.service.ts
  src/floor/dtos/create-floor.dto.ts
  src/floor/dtos/update-floor.dto.ts
  src/floor/floor.controller.ts
  src/floor/floor.entity.ts
  src/floor/floor.module.ts
  src/floor/floor.repository.ts
  src/floor/floor.service.ts
Labels: enhancement

#31 질문 및 답변 API 구현
  src/answer/answer.controller.ts
  src/answer/answer.entity.ts
  src/answer/answer.module.ts
  src/answer/answer.repository.ts
  src/answer/answer.service.ts
  src/answer/dtos/create-answer.dto.ts
  src/answer/dtos/search-answer.dto.ts
  src/answer/dtos/update-answer.dto.ts
  src/app.module.ts
  src/common/utils/errors/ErrorMessage.ts
  src/config/config.service.ts
  src/main.ts
  src/notification/notification.entity.ts
  src/question/dtos/create-question.dto.ts
  src/question/dtos/search-question.dto.ts
  src/question/dtos/update-question.dto.ts
  src/question/question.controller.ts
  src/question/question.entity.ts
  src/question/question.module.ts
  src/question/question.repository.ts
  src/question/question.service.ts
  src/user/user.entity.ts
Labels: enhancement

#35 User 검색 API 구현
  src/user/dtos/search-user.dto.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: enhancement

#37 User 인증 및 권한 설정
  src/auth/auth.controller.ts
  src/config/config.service.ts
  src/config/swagger/setup.ts
  src/user/user.controller.ts
Labels: enhancement

#43 [PR] 예약 조회 시 관련 정보 추가 반환
  src/floor/floor.entity.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/room/room.entity.ts
  src/seat/seat.entity.ts
Labels: enhancement

#44 [PR] 배포 0.0.3
  src/answer/answer.service.ts
  src/app.controller.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dtos/login-user.dto.ts
  src/common/utils/errors/http-message.enum.ts
  src/facility/facility.service.ts
  src/floor/floor.entity.ts
  src/floor/floor.service.ts
  src/question/question.service.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/room/room.entity.ts
  src/room/room.service.ts
  src/seat/seat.entity.ts
  src/seat/seat.service.ts
  src/user/user.service.ts
Labels: release

#47 [PR] 예약 관련 오류 수정
  src/reservation/dtos/create-reservation.dto.ts
  src/reservation/dtos/create-room-reservation.dto.ts
  src/reservation/dtos/create-seat-reservation.dto.ts
  src/reservation/reservation.entity.ts
  src/reservation/reservation.module.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/room/room.entity.ts
  src/seat/seat.entity.ts
Labels: bug

#50 [PR] 0.0.3 배포
  package.json
  src/answer/answer.entity.ts
  src/answer/answer.repository.ts
  src/facility/facility.entity.ts
  src/floor/dtos/create-floor.dto.ts
  src/floor/floor.controller.ts
  src/floor/floor.entity.ts
  src/question/question.entity.ts
  src/reservation/dtos/create-reservation.dto.ts
  src/reservation/dtos/create-room-reservation.dto.ts
  src/reservation/dtos/create-seat-reservation.dto.ts
  src/reservation/reservation.entity.ts
  src/reservation/reservation.module.ts
  src/reservation/reservation.service.ts
  src/room/dtos/create-room.dto.ts
  src/room/room.entity.ts
  src/seat/seat.entity.ts
Labels: release

#71 [PR] ESL 관련 작업
  .gitignore
  package-lock.json
  package.json
  src/question/question.repository.ts
  src/question/question.service.ts
  src/reservation/dtos/create-reservation.dto.ts
  src/reservation/dtos/create-room-reservation.dto.ts
  src/reservation/dtos/create-seat-reservation.dto.ts
  src/reservation/dtos/search-reservation.dto.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.entity.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/task/task.module.ts
  src/task/task.service.ts
Labels: enhancement

#80 [PR] ESL converter 구현
  src/reservation/reservation.repository.ts
  src/task/task.module.ts
  src/task/task.service.ts
Labels: enhancement

#82 [PR] 0.1.0 배포
  package.json
  src/config/config.service.ts
  src/notification/notification.entity.ts
  src/question/question.entity.ts
  src/reservation/dtos/create-room-reservation.dto.ts
  src/reservation/dtos/create-seat-reservation.dto.ts
  src/reservation/dtos/search-reservation.dto.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.entity.ts
  src/reservation/reservation.repository.ts
  src/reservation/reservation.service.ts
  src/room/room.entity.ts
  src/room/room.repository.ts
  src/seat/seat.entity.ts
  src/seat/seat.repository.ts
  src/task/task.module.ts
  src/task/task.service.ts
Labels: release

#84 [PR] 이슈 해결 배포
  src/common/utils/errors/http-message.enum.ts
  src/reservation/dtos/create-reservation.dto.ts
  src/reservation/dtos/create-seat-reservation.dto.ts
  src/reservation/reservation.service.ts
  src/room/dtos/create-room.dto.ts
  src/room/room.entity.ts
  src/seat/dtos/create-seat.dto.ts
  src/seat/seat.entity.ts
  src/seat/seat.repository.ts
  src/user/user.entity.ts
  src/user/user.service.ts
Labels: release
